apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: route
spec:
  host: app-demo.apps.openshift.sebastian-colomar.es
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: svc
