namespace: phpinfo-helm-sebastian-2
svc:
  - name: svc
    ports:
      - port: 5050
    selector:
      app: deploy
routes:
  - name: route
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: svc
