cm:
  - name: cm
    data:
      index.php: <?php phpinfo();?>
namespace: phpinfo-helm-sebastian-2
routes:
  - name: route
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: svc
svc:
  - name: svc
    ports:
      - port: 5050
    selector:
      app: deploy
